# see package.yml for usage 
name: 'ROS Docs'
description: 'Documentation generation for ROS Projects'
inputs:
  path:  
    description: 'The path, relative from root of the project, to the packages'
    required: false
    default: '.'
outputs:
  artifact-path:
    description: 'The location of the generated files.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: # see entrypoint.sh for the recipient of these - order matters
    - ${{ inputs.path }}

